### ISSUE TITLE
notation confusion 

### ISSUE THREAD

**Issue by luoyuchenmlcv** [PRBonn/3DUIS#1]
Thanks for sharing your great work!
In the paper, I am quite confused with the formula below: 
![image](https://user-images.githubusercontent.com/102636806/190984080-c322550c-c509-4334-8c80-bc0982e133a0.png)
These are for calculating mean value δ of all the feature vectors F_k={fk1, fk2, ..., fkm}.
If I understand correctly, fki is a feature vector of a point p in ROI S^K, an element of F_k, and
δ should simply be the mean feature vector by averaging over F_k. Why there are two averaging in your formula?

**Comment by nuneslu** [comment]
Hi, so fk is the average feature vector from all the points inside a proposal. Then, to compute the saliency we need one value only in this case δ, which is the average of all the values in the feature vector fk. So we basically compute the average twice, once over all the proposal points feature vectors, and then once more over the average proposal feature vector.
