### ISSUE TITLE
Cuda version and GPU

### ISSUE THREAD

**Issue by Cipher-zzz** [PRBonn/3DUIS#2]
Thanks for your great work! 

Could you please provide the Cuda version and GPU used in the project? That helps a lot in installing the code.

**Comment by nuneslu** [comment]
Hi! Sure, the CUDA version was 11.1 with torch 1.9.0. The GPU used was a GeForce GTX 1080 Ti.

**Comment by Cipher-zzz** [comment]
> Hi! Sure, the CUDA version was 11.1 with torch 1.9.0. The GPU used was a GeForce GTX 1080 Ti.

Thank you!
